<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/php-di/php-di/src/functions.php';
require_once __DIR__ . '/symfony/polyfill-php81/bootstrap.php';
